# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tel', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
