# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='sortid',
        ),
    ]
