# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_wheel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleTypeid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlename', models.CharField(max_length=100)),
                ('typeid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='whiteSpirit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('productid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('typeid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'zj_whiteSpirit',
            },
        ),
    ]
