# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_titletypeid_whitespirit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleTypeid',
        ),
    ]
