# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_goodslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('addr', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'zj_users',
            },
        ),
        migrations.DeleteModel(
            name='GoodsList',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
